name: VS 2022

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: ["release", "debug"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-vcpkg-archives-${{ hashFiles('vcpkg.json') }}

      - name: Set up vcpkg
        run: |
          git -C C:\vcpkg fetch
          vcpkg version
          vcpkg integrate install

      - name: Set up MSBuild logger
        run: |
          Invoke-WebRequest -Uri https://github.com/reupen/msbuild-github-logger/releases/download/v1.0.0/Reupen.MSBuild.GitHubLogger.dll -OutFile "$Env:Temp\Reupen.MSBuild.GitHubLogger.dll"

      - name: Build
        run: |
          msbuild /m '/p:Platform=Win32;Configuration=${{ matrix.configuration }}' "/logger:$Env:Temp\Reupen.MSBuild.GitHubLogger.dll" vc17\console_panel.sln
